/**
 * ValidationSnapshot Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/validations.openapi.types.js";
import { schemas } from "../schemas/validations.schemas.js";

/**
 * Entity: ValidationSnapshotEntity
 * Description: Represents the ValidationSnapshot domain model.
 * Source: schemas.ValidationSnapshot
 * Type: Domain Entity (API)
 */
export const ValidationSnapshotEntitySchema = schemas.ValidationSnapshot;
export type ValidationSnapshotEntity = components["schemas"]["ValidationSnapshot"];
