/**
 * CreateSubmission DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { ModelSubmissionRequest } from "@fedbounty/core/submissions";
import { submissionsSchemas } from "@fedbounty/core/submissions";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sub";

export function createCreateSubmissionRequest(overrides: Partial<ModelSubmissionRequest> = {}) {
  const raw = {
    bountyId: overrides.bountyId ?? `bty_${ulid().toLowerCase()}`,
    modelCid: overrides.modelCid ?? faker.string.uuid(),
    workerId: overrides.workerId ?? `wrk_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return submissionsSchemas.ModelSubmissionRequest.parse(raw);
}
