/**
 * GetSubmission DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetModelSubmissionParams } from "@fedbounty/core/submissions";

export function createGetSubmissionRequest(overrides: Partial<GetModelSubmissionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
