/**
 * Handlers for BountyAudit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { GetBountyAuditReportInput } from "@fedbounty/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reports/bounty-audit
 * Operation: getBountyAuditReport
 */
export async function getBountyAuditReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { bountyId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBountyAuditReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.bountyAudits.get.execute(input);
  return reply.code(200).send(result);
}


