/**
 * Handlers for Report
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportingDomainModule } from "../dependencies/reporting-ddd.dependencies.js";
import type { PeriodReportCreateRequest } from "@fedbounty/core/reporting/types";
import type { CreatePeriodReportInput, GetReportInput, ListReportsInput } from "@fedbounty/services/reporting";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reports
 * Operation: listReports
 */
export async function listReports(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListReportsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.reports.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/reports
 * Operation: createPeriodReport
 */
export async function createPeriodReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PeriodReportCreateRequest }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreatePeriodReportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/reports/{reportId}
 * Operation: getReport
 */
export async function getReport(
  request: FastifyRequest<{ Params: { reportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetReportInput = {
    reportId: request.params.reportId,
  };
  const result = await deps.useCases.reports.get.execute(input);
  return reply.code(200).send(result);
}


