/**
 * Routes for Close
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { closeBounty } from "../handlers/close.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function closeRoutes(fastify: FastifyInstance) {
  // POST /v1/bounties/{bountyId}/close (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/bounties/:bountyId/close",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { bountyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBountiesDependenciesForRequest();
        await closeBounty(request, reply, deps);
      });
    }
  );


}
