/**
 * CreateEnrollment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { WorkerEnrollmentRequest } from "@fedbounty/core/bounties";
import { bountiesSchemas } from "@fedbounty/core/bounties";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "bty";

export function createCreateEnrollmentRequest(overrides: Partial<WorkerEnrollmentRequest> = {}) {
  const raw = {
    environmentAttestation: overrides.environmentAttestation ?? faker.lorem.word(),
    termsAccepted: overrides.termsAccepted ?? faker.datatype.boolean(),
    workerId: overrides.workerId ?? `wrk_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return bountiesSchemas.WorkerEnrollmentRequest.parse(raw);
}
