/**
 * ExecuteUpdateBounty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateBounty Use Case
 *
 * DDD: Application use case for update Bounty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateBountyInput, UpdateBountyOutput } from "../dto/bounty.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { BountyRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateBounty {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly bounty: BountyRepository
  ) {}

  async execute(input: UpdateBountyInput): Promise<UpdateBountyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.btyId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).bountyId) {
      throw new ValidationError("bountyId is required");
    }
    const bountyId = (input as any).bountyId;

    // Load existing entity
    const existing = await this.bounty.getBounty({ bountyId: bountyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${bountyId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.bounty.updateBounty({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateBountyOutput;
  }
}
