/**
 * ExecuteGetBounty - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBounty Use Case
 *
 * DDD: Application use case for get Bounty.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBountyInput, GetBountyOutput } from "../dto/bounty.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { BountyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetBounty {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly bounty: BountyRepository
  ) {}

  async execute(input: GetBountyInput): Promise<GetBountyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.btyId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).bountyId) {
      throw new ValidationError("bountyId is required");
    }
    const bountyId = (input as any).bountyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.bounty.getBounty({ bountyId: bountyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${bountyId}`);
    }

    return entity as GetBountyOutput;
  }
}
