/**
 * ExecuteListBountyEnrollments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListBountyEnrollments Use Case
 *
 * DDD: Application use case for list Enrollment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListBountyEnrollmentsInput, ListBountyEnrollmentsOutput } from "../dto/enrollment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { EnrollmentRepository } from "../ports";

export class ExecuteListBountyEnrollments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly enrollment: EnrollmentRepository
  ) {}

  async execute(input: ListBountyEnrollmentsInput): Promise<ListBountyEnrollmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.btyId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.enrollment.listBountyEnrollments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListBountyEnrollmentsOutput;
  }
}
