/**
 * Handlers for Payout
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { RewardsDomainModule } from "../dependencies/rewards-ddd.dependencies.js";
import type { RewardPayoutRequest } from "@fedbounty/core/rewards/types";
import type { ExecuteRewardPayoutInput, GetRewardPayoutInput, ListRewardPayoutsInput } from "@fedbounty/services/rewards";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/rewards/payouts
 * Operation: listRewardPayouts
 */
export async function listRewardPayouts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], bountyId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: RewardsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRewardPayoutsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.payouts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/rewards/payouts
 * Operation: executeRewardPayout
 */
export async function executeRewardPayout(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: RewardPayoutRequest }>,
  reply: FastifyReply,
  deps: RewardsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExecuteRewardPayoutInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.payouts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/rewards/payouts/{payoutId}
 * Operation: getRewardPayout
 */
export async function getRewardPayout(
  request: FastifyRequest<{ Params: { payoutId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: RewardsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRewardPayoutInput = {
    payoutId: request.params.payoutId,
  };
  const result = await deps.useCases.payouts.get.execute(input);
  return reply.code(200).send(result);
}


