/**
 * GetReport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getReport } from "@fedbounty/api-server/domains/reporting/handlers";
import type { ReportingDDDDependencies } from "@fedbounty/api-server/domains/reporting";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { REPORTING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetReport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReportingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReportingDDDDependencies>(
      REPORTING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetReport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { reportId: entity.id };

    await getReport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetReport.execute).toHaveBeenCalledWith(expect.objectContaining({ reportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { reportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetReport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getReport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
