/**
 * CreateReport DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PeriodReportCreateRequest } from "@fedbounty/core/reporting";
import { reportingSchemas } from "@fedbounty/core/reporting";

export function createCreateReportRequest(overrides: Partial<PeriodReportCreateRequest> = {}) {
  const raw = {
    period: overrides.period ?? faker.lorem.word(),
    ...overrides,
  };

  return reportingSchemas.PeriodReportCreateRequest.parse(raw);
}
