/**
 * ExecuteGetEscrowAccount - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetEscrowAccount Use Case
 *
 * DDD: Application use case for get Escrow.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetEscrowAccountInput, GetEscrowAccountOutput } from "../dto/escrow.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { EscrowRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetEscrowAccount {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escrow: EscrowRepository
  ) {}

  async execute(input: GetEscrowAccountInput): Promise<GetEscrowAccountOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rwdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).bountyId) {
      throw new ValidationError("bountyId is required");
    }
    const bountyId = (input as any).bountyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.escrow.getEscrowAccount({ bountyId: bountyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${bountyId}`);
    }

    return entity as GetEscrowAccountOutput;
  }
}
