/**
 * ExecuteGetRewardPayout - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRewardPayout Use Case
 *
 * DDD: Application use case for get Payout.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRewardPayoutInput, GetRewardPayoutOutput } from "../dto/payout.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { PayoutRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetRewardPayout {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly payout: PayoutRepository
  ) {}

  async execute(input: GetRewardPayoutInput): Promise<GetRewardPayoutOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rwdId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).payoutId) {
      throw new ValidationError("payoutId is required");
    }
    const payoutId = (input as any).payoutId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.payout.getRewardPayout({ payoutId: payoutId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${payoutId}`);
    }

    return entity as GetRewardPayoutOutput;
  }
}
