/**
 * QuarantineModelSubmission handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { quarantineModelSubmission } from "@fedbounty/api-server/domains/submissions/handlers";
import type { SubmissionsDDDDependencies } from "@fedbounty/api-server/domains/submissions";
import { createCreateQuarantineRequest } from "@fedbounty/factories/submissions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { SUBMISSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("QuarantineModelSubmission", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SubmissionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SubmissionsDDDDependencies>(
      SUBMISSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateQuarantineRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeQuarantineModelSubmission, "execute").mockResolvedValue(useCaseResult);

    await quarantineModelSubmission(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeQuarantineModelSubmission.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
