/**
 * Rewards DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Rewards Domain Module - Composition root
 *
 * DDD: Composition root for rewards domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EscrowRepositoryAdapter,
  PauseRepositoryAdapter,
  PayoutRepositoryAdapter,
} from "@fedbounty/adapters/rewards";
import { getIdGeneratorService } from "@fedbounty/adapters";
import type { AdapterDynamoDBClient } from "@fedbounty/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExecuteRewardPayout,
  ExecuteGetEscrowAccount,
  ExecuteGetRewardPayout,
  ExecuteListRewardPayouts,
  ExecutePauseEscrow,
} from "@fedbounty/services/rewards/usecases";
// Ports (interfaces)
import type {
  EscrowRepository,
  PauseRepository,
  PayoutRepository,
} from "@fedbounty/services/rewards/ports";

export interface RewardsDomainModule {
  repos: {
    escrows: EscrowRepository;
    pauses: PauseRepository;
    payouts: PayoutRepository;
  };
  useCases: {
    escrows: {
      get: ExecuteGetEscrowAccount;
    };
    pauses: {
      get: ExecutePauseEscrow;
    };
    payouts: {
      create: ExecuteExecuteRewardPayout;
      get: ExecuteGetRewardPayout;
      list: ExecuteListRewardPayouts;
    };
  };
}

export function buildRewardsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): RewardsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      escrows?: EscrowRepository;
      pauses?: PauseRepository;
      payouts?: PayoutRepository;
    } = {};

    obj.escrows = new EscrowRepositoryAdapter(dynamoClient);
    obj.pauses = new PauseRepositoryAdapter(dynamoClient);
    obj.payouts = new PayoutRepositoryAdapter(dynamoClient);
    return {
      escrows: obj.escrows!,
      pauses: obj.pauses!,
      payouts: obj.payouts!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    escrows: {
      get: new ExecuteGetEscrowAccount(executionContext, idGenerator, repos.escrows),
    },
    pauses: {
      get: new ExecutePauseEscrow(executionContext, idGenerator, repos.pauses),
    },
    payouts: {
      create: new ExecuteExecuteRewardPayout(executionContext, idGenerator, repos.payouts),
      get: new ExecuteGetRewardPayout(executionContext, idGenerator, repos.payouts),
      list: new ExecuteListRewardPayouts(executionContext, idGenerator, repos.payouts),
    },
  };
  return { repos, useCases: useCases as RewardsDomainModule["useCases"] };
}
