/**
 * Handlers for Dispute
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ValidationsDomainModule } from "../dependencies/validations-ddd.dependencies.js";
import type { DisputeOpenRequest } from "@fedbounty/core/validations/types";
import type { GetScoringDisputeInput, OpenScoringDisputeInput } from "@fedbounty/services/validations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/disputes
 * Operation: openScoringDispute
 */
export async function openScoringDispute(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DisputeOpenRequest }>,
  reply: FastifyReply,
  deps: ValidationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenScoringDisputeInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disputes.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/disputes/{disputeId}
 * Operation: getScoringDispute
 */
export async function getScoringDispute(
  request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ValidationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetScoringDisputeInput = {
    disputeId: request.params.disputeId,
  };
  const result = await deps.useCases.disputes.get.execute(input);
  return reply.code(200).send(result);
}


