/**
 * Handlers for ValidationSnapshot
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ValidationsDomainModule } from "../dependencies/validations-ddd.dependencies.js";
import type { ValidationSnapshotCreateRequest } from "@fedbounty/core/validations/types";
import type { CreateValidationSnapshotInput, GetValidationSnapshotInput } from "@fedbounty/services/validations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/validation-snapshots
 * Operation: createValidationSnapshot
 */
export async function createValidationSnapshot(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ValidationSnapshotCreateRequest }>,
  reply: FastifyReply,
  deps: ValidationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateValidationSnapshotInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.validationSnapshots.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/validation-snapshots/{snapshotId}
 * Operation: getValidationSnapshot
 */
export async function getValidationSnapshot(
  request: FastifyRequest<{ Params: { snapshotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ValidationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetValidationSnapshotInput = {
    snapshotId: request.params.snapshotId,
  };
  const result = await deps.useCases.validationSnapshots.get.execute(input);
  return reply.code(200).send(result);
}


