/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as bountiesRoutes from "../../domains/bounties/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as lineageRoutes from "../../domains/lineage/routes/index.js";
import * as reportingRoutes from "../../domains/reporting/routes/index.js";
import * as rewardsRoutes from "../../domains/rewards/routes/index.js";
import * as submissionsRoutes from "../../domains/submissions/routes/index.js";
import * as validationsRoutes from "../../domains/validations/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "bounties", mod: bountiesRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "signupRoutes", "sessionRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "lineage", mod: lineageRoutes },
  { domain: "reporting", mod: reportingRoutes },
  { domain: "rewards", mod: rewardsRoutes },
  { domain: "submissions", mod: submissionsRoutes },
  { domain: "validations", mod: validationsRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
