/**
 * BountyAuditRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BountyAuditRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BountyAuditRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BountyAuditRepository,
} from "@fedbounty/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BountyAuditRepositoryDdb } from "./bounty-audit-repository.ddb.js";

/**
 * BountyAuditRepositoryAdapter
 *
 * Implements BountyAuditRepository port for infrastructure layer.
 */
export class BountyAuditRepositoryAdapter implements BountyAuditRepository {
  private readonly ddb: BountyAuditRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BountyAuditRepositoryDdb(this.dynamoClient);
  }

  async getBountyAuditReport(input: Parameters<BountyAuditRepository['getBountyAuditReport']>[0]): Promise<Awaited<ReturnType<BountyAuditRepository['getBountyAuditReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBountyAuditReport(input);
  }
}
