/**
 * ReportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReportRepository,
} from "@fedbounty/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReportRepositoryDdb } from "./report-repository.ddb.js";

/**
 * ReportRepositoryAdapter
 *
 * Implements ReportRepository port for infrastructure layer.
 */
export class ReportRepositoryAdapter implements ReportRepository {
  private readonly ddb: ReportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReportRepositoryDdb(this.dynamoClient);
  }

  async listReports(input: Parameters<ReportRepository['listReports']>[0]): Promise<Awaited<ReturnType<ReportRepository['listReports']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReports(input);
  }

  async createPeriodReport(input: Parameters<ReportRepository['createPeriodReport']>[0]): Promise<Awaited<ReturnType<ReportRepository['createPeriodReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createPeriodReport(input);
  }

  async getReport(input: Parameters<ReportRepository['getReport']>[0]): Promise<Awaited<ReturnType<ReportRepository['getReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReport(input);
  }
}
