/**
 * Routes for Payout
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { executeRewardPayout, getRewardPayout, listRewardPayouts } from "../handlers/payout.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { RewardPayoutRequest } from "@fedbounty/core/rewards/types";

// Fastify types are available globally
export async function payoutRoutes(fastify: FastifyInstance) {
  // POST /v1/rewards/payouts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/rewards/payouts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: RewardPayoutRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRewardsDependenciesForRequest();
        await executeRewardPayout(request, reply, deps);
      });
    }
  );


  // GET /v1/rewards/payouts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/rewards/payouts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRewardsDependenciesForRequest();
        await listRewardPayouts(request, reply, deps);
      });
    }
  );


  // GET /v1/rewards/payouts/{payoutId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/rewards/payouts/:payoutId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { payoutId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getRewardsDependenciesForRequest();
        await getRewardPayout(request, reply, deps);
      });
    }
  );


}
