/**
 * PublishBounty handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { publishBounty } from "@fedbounty/api-server/domains/bounties/handlers";
import type { BountiesDDDDependencies } from "@fedbounty/api-server/domains/bounties";
import { createCreatePublishRequest } from "@fedbounty/factories/bounties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { BOUNTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("PublishBounty", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BountiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BountiesDDDDependencies>(
      BOUNTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePublishRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePublishBounty, "execute").mockResolvedValue(useCaseResult);

    await publishBounty(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePublishBounty.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
