/**
 * ListValidation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEvaluationResultsParams } from "@fedbounty/core/validations";

export function createListValidationRequest(overrides: Partial<ListEvaluationResultsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
