/**
 * ExecuteQuarantineModelSubmission - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteQuarantineModelSubmission Use Case
 *
 * DDD: Application use case for get Quarantine.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { QuarantineModelSubmissionInput, QuarantineModelSubmissionOutput } from "../dto/quarantine.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { QuarantineRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteQuarantineModelSubmission {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quarantine: QuarantineRepository
  ) {}

  async execute(input: QuarantineModelSubmissionInput): Promise<QuarantineModelSubmissionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).submissionId) {
      throw new ValidationError("submissionId is required");
    }
    const submissionId = (input as any).submissionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.quarantine.quarantineModelSubmission({ submissionId: submissionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${submissionId}`);
    }

    return entity as QuarantineModelSubmissionOutput;
  }
}
