/**
 * ExecuteListModelSubmissions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListModelSubmissions Use Case
 *
 * DDD: Application use case for list Submission.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListModelSubmissionsInput, ListModelSubmissionsOutput } from "../dto/submission.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { SubmissionRepository } from "../ports";

export class ExecuteListModelSubmissions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly submission: SubmissionRepository
  ) {}

  async execute(input: ListModelSubmissionsInput): Promise<ListModelSubmissionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.submission.listModelSubmissions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListModelSubmissionsOutput;
  }
}
