/**
 * ExecuteSubmitModelArtifact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitModelArtifact Use Case
 *
 * DDD: Application use case for create Submission.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitModelArtifactInput, SubmitModelArtifactOutput } from "../dto/submission.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { SubmissionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitModelArtifact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly submission: SubmissionRepository
  ) {}

  async execute(input: SubmitModelArtifactInput): Promise<SubmitModelArtifactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.subId();

    // All field names extracted from OpenAPI spec: bountyId, modelCid, publicMetricHint, workerId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.bountyId) {
      throw new ValidationError("bountyId is required");
    }
    if (!input.modelCid) {
      throw new ValidationError("modelCid is required");
    }
    if (!input.workerId) {
      throw new ValidationError("workerId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (submissions domain)
    const entityId = this.idGenerator.subId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.submission.submitModelArtifact({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitModelArtifactOutput;
  }
}
