/**
 * PinRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PinRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PinRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PinRepository,
} from "@fedbounty/services/lineage";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PinRepositoryDdb } from "./pin-repository.ddb.js";

/**
 * PinRepositoryAdapter
 *
 * Implements PinRepository port for infrastructure layer.
 */
export class PinRepositoryAdapter implements PinRepository {
  private readonly ddb: PinRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PinRepositoryDdb(this.dynamoClient);
  }

  async pinCanonicalModelVersion(input: Parameters<PinRepository['pinCanonicalModelVersion']>[0]): Promise<Awaited<ReturnType<PinRepository['pinCanonicalModelVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.pinCanonicalModelVersion(input);
  }
}
