/**
 * ValidationSnapshot Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ValidationSnapshotEntity } from "@fedbounty/core/validations/models/index.js";
import { validationsSchemas } from "@fedbounty/core/validations";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "vld";

export function createValidationSnapshot(overrides: Partial<ValidationSnapshotEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    frozen: overrides.frozen ?? faker.datatype.boolean(),
    metricName: overrides.metricName ?? faker.lorem.word(),
    snapshotId: overrides.snapshotId ?? `snp_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return validationsSchemas.ValidationSnapshot.parse(raw);
}

export function validationSnapshotBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createValidationSnapshot(overrides));
}
