/**
 * CreateVersion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { ulid } from "ulid";
import type { ModelMergeRequest } from "@fedbounty/core/lineage";
import { lineageSchemas } from "@fedbounty/core/lineage";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "lng";

export function createCreateVersionRequest(overrides: Partial<ModelMergeRequest> = {}) {
  const raw = {
    bountyId: overrides.bountyId ?? `bty_${ulid().toLowerCase()}`,
    submissionIds: overrides.submissionIds ?? [],
    ...overrides,
  };

  return lineageSchemas.ModelMergeRequest.parse(raw);
}
