/**
 * GetVersion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetModelVersionParams } from "@fedbounty/core/lineage";

export function createGetVersionRequest(overrides: Partial<GetModelVersionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
