/**
 * Handlers for Bounty
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BountiesDomainModule } from "../dependencies/bounties-ddd.dependencies.js";
import type { BountyCreateRequest, BountyUpdateRequest } from "@fedbounty/core/bounties/types";
import type { CreateBountyInput, GetBountyInput, ListBountiesInput, UpdateBountyInput } from "@fedbounty/services/bounties";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/bounties
 * Operation: listBounties
 */
export async function listBounties(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBountiesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.bounties.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/bounties
 * Operation: createBounty
 */
export async function createBounty(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: BountyCreateRequest }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateBountyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.bounties.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/bounties/{bountyId}
 * Operation: getBounty
 */
export async function getBounty(
  request: FastifyRequest<{ Params: { bountyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetBountyInput = {
    bountyId: request.params.bountyId,
  };
  const result = await deps.useCases.bounties.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/bounties/{bountyId}
 * Operation: updateBounty
 */
export async function updateBounty(
  request: FastifyRequest<{ Params: { bountyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: BountyUpdateRequest }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateBountyInput = {
    bountyId: request.params.bountyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.bounties.update.execute(input);
  return reply.code(200).send(result);
}


