/**
 * Handlers for Enrollment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BountiesDomainModule } from "../dependencies/bounties-ddd.dependencies.js";
import type { WorkerEnrollmentRequest } from "@fedbounty/core/bounties/types";
import type { EnrollWorkerInput, ListBountyEnrollmentsInput } from "@fedbounty/services/bounties";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/bounties/{bountyId}/enrollments
 * Operation: listBountyEnrollments
 */
export async function listBountyEnrollments(
  request: FastifyRequest<{ Params: { bountyId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListBountyEnrollmentsInput = {
    bountyId: request.params.bountyId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.enrollments.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/bounties/{bountyId}/enrollments
 * Operation: enrollWorker
 */
export async function enrollWorker(
  request: FastifyRequest<{ Params: { bountyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: WorkerEnrollmentRequest }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: EnrollWorkerInput = {
    bountyId: request.params.bountyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.enrollments.create.execute(input);
  return reply.code(201).send(result);
}


