/**
 * Handlers for Freeze
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BountiesDomainModule } from "../dependencies/bounties-ddd.dependencies.js";
import type { BountyFreezeRequest } from "@fedbounty/core/bounties/types";
import type { FreezeBountyInput } from "@fedbounty/services/bounties";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/bounties/{bountyId}/freeze
 * Operation: freezeBounty
 */
export async function freezeBounty(
  request: FastifyRequest<{ Params: { bountyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: BountyFreezeRequest }>,
  reply: FastifyReply,
  deps: BountiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: FreezeBountyInput = {
    bountyId: request.params.bountyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.freezes.get.execute(input);
  return reply.code(200).send(result);
}


