/**
 * BountyAuditRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BountyAuditRepository Port
 *
 * DDD: Application port for bountyauditrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetBountyAuditReportInput, GetBountyAuditReportOutput } from "../dto/bounty-audit.dto";
export interface BountyAuditRepository {
  getBountyAuditReport(input: GetBountyAuditReportInput): Promise<GetBountyAuditReportOutput>;
}

export type { GetBountyAuditReportInput, GetBountyAuditReportOutput } from "../dto/bounty-audit.dto";
