/**
 * Routes for Version
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getModelVersion, listModelVersions, mergeModelVersion } from "../handlers/version.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ModelMergeRequest } from "@fedbounty/core/lineage/types";

// Fastify types are available globally
export async function versionRoutes(fastify: FastifyInstance) {
  // GET /v1/lineage/versions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/lineage/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLineageDependenciesForRequest();
        await listModelVersions(request, reply, deps);
      });
    }
  );


  // POST /v1/lineage/versions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/lineage/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ModelMergeRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLineageDependenciesForRequest();
        await mergeModelVersion(request, reply, deps);
      });
    }
  );


  // GET /v1/lineage/versions/{versionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/lineage/versions/:versionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { versionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLineageDependenciesForRequest();
        await getModelVersion(request, reply, deps);
      });
    }
  );


}
