/**
 * ExecuteGetValidationSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetValidationSnapshot Use Case
 *
 * DDD: Application use case for get ValidationSnapshot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetValidationSnapshotInput, GetValidationSnapshotOutput } from "../dto/validation-snapshot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { ValidationSnapshotRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetValidationSnapshot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly validationSnapshot: ValidationSnapshotRepository
  ) {}

  async execute(input: GetValidationSnapshotInput): Promise<GetValidationSnapshotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vldId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).snapshotId) {
      throw new ValidationError("snapshotId is required");
    }
    const snapshotId = (input as any).snapshotId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.validationSnapshot.getValidationSnapshot({ snapshotId: snapshotId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${snapshotId}`);
    }

    return entity as GetValidationSnapshotOutput;
  }
}
