/**
 * ExecuteRunHoldoutValidation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRunHoldoutValidation Use Case
 *
 * DDD: Application use case for create Validation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RunHoldoutValidationInput, RunHoldoutValidationOutput } from "../dto/validation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { ValidationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRunHoldoutValidation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly validation: ValidationRepository
  ) {}

  async execute(input: RunHoldoutValidationInput): Promise<RunHoldoutValidationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.vldId();

    // All field names extracted from OpenAPI spec: submissionId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.submissionId) {
      throw new ValidationError("submissionId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (validations domain)
    const entityId = this.idGenerator.vldId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.validation.runHoldoutValidation({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RunHoldoutValidationOutput;
  }
}
