/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { QuarantineModelSubmissionParams, SubmissionQuarantineRequest } from "@fedbounty/core/submissions/types";

export type QuarantineModelSubmissionInput = QuarantineModelSubmissionParams & SubmissionQuarantineRequest;

export type QuarantineModelSubmissionOutput = {};
