/**
 * Submission DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Submission DTOs
 *
 * DDD: Application DTOs for Submission use cases.
 */

import type { GetModelSubmissionParams, ListModelSubmissionsParams, ModelSubmissionRequest } from "@fedbounty/core/submissions/types";

export type ListModelSubmissionsInput = ListModelSubmissionsParams;

export type SubmitModelArtifactInput = ModelSubmissionRequest;

export type GetModelSubmissionInput = GetModelSubmissionParams;

export type ListModelSubmissionsOutput = {};

export type SubmitModelArtifactOutput = {};

export type GetModelSubmissionOutput = {};
