/**
 * ExecuteCreatePeriodReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreatePeriodReport Use Case
 *
 * DDD: Application use case for create Report.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreatePeriodReportInput, CreatePeriodReportOutput } from "../dto/report.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { ReportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreatePeriodReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly report: ReportRepository
  ) {}

  async execute(input: CreatePeriodReportInput): Promise<CreatePeriodReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: bountyId, period, summary
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.period) {
      throw new ValidationError("period is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (reporting domain)
    const entityId = this.idGenerator.rptId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.report.createPeriodReport({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreatePeriodReportOutput;
  }
}
