/**
 * Routes for Report
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createPeriodReport, getReport, listReports } from "../handlers/report.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { PeriodReportCreateRequest } from "@fedbounty/core/reporting/types";

// Fastify types are available globally
export async function reportRoutes(fastify: FastifyInstance) {
  // POST /v1/reports (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/reports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: PeriodReportCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await createPeriodReport(request, reply, deps);
      });
    }
  );


  // GET /v1/reports (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await listReports(request, reply, deps);
      });
    }
  );


  // GET /v1/reports/{reportId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/reports/:reportId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { reportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReportingDependenciesForRequest();
        await getReport(request, reply, deps);
      });
    }
  );


}
