/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BountyAuditRepositoryAdapter,
  ReportRepositoryAdapter,
} from "@fedbounty/adapters/reporting";
import { getIdGeneratorService } from "@fedbounty/adapters";
import type { AdapterDynamoDBClient } from "@fedbounty/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePeriodReport,
  ExecuteGetReport,
  ExecuteListReports,
} from "@fedbounty/services/reporting/usecases";
// Ports (interfaces)
import type {
  BountyAuditRepository,
  ReportRepository,
} from "@fedbounty/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    bountyAudits: BountyAuditRepository;
    reports: ReportRepository;
  };
  useCases: {
    reports: {
      create: ExecuteCreatePeriodReport;
      get: ExecuteGetReport;
      list: ExecuteListReports;
    };
  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      bountyAudits?: BountyAuditRepository;
      reports?: ReportRepository;
    } = {};

    obj.bountyAudits = new BountyAuditRepositoryAdapter(dynamoClient);
    obj.reports = new ReportRepositoryAdapter(dynamoClient);
    return {
      bountyAudits: obj.bountyAudits!,
      reports: obj.reports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    reports: {
      create: new ExecuteCreatePeriodReport(executionContext, idGenerator, repos.reports),
      get: new ExecuteGetReport(executionContext, idGenerator, repos.reports),
      list: new ExecuteListReports(executionContext, idGenerator, repos.reports),
    },
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
