/**
 * VersionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VersionRepository Port
 *
 * DDD: Application port for versionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput, MergeModelVersionInput, MergeModelVersionOutput } from "../dto/version.dto";
export interface VersionRepository {
  listModelVersions(input: ListModelVersionsInput): Promise<ListModelVersionsOutput>;
  mergeModelVersion(input: MergeModelVersionInput): Promise<MergeModelVersionOutput>;
  getModelVersion(input: GetModelVersionInput): Promise<GetModelVersionOutput>;
}

export type { GetModelVersionInput, GetModelVersionOutput, ListModelVersionsInput, ListModelVersionsOutput, MergeModelVersionInput, MergeModelVersionOutput } from "../dto/version.dto";
