/**
 * Repository interface for ValidationSnapshot
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ValidationSnapshotEntity
} from "../models/validation-snapshot.entity.js";
import type {
  ValidationSnapshotCreateRequest
} from "../types/index.js";
/**
 * ValidationSnapshotRepository Interface
 */
export interface ValidationSnapshotRepository extends CreateReadRepository<ValidationSnapshotEntity, ValidationSnapshotCreateRequest, string, Record<string, never>> {

}
