/**
 * UpdateBounty DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { BountyUpdateRequest } from "@fedbounty/core/bounties";
import { bountiesSchemas } from "@fedbounty/core/bounties";

export function createUpdateBountyRequest(overrides: Partial<BountyUpdateRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return bountiesSchemas.BountyUpdateRequest.parse(raw);
}
