/**
 * DisputeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisputeRepository Port
 *
 * DDD: Application port for disputerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetScoringDisputeInput, GetScoringDisputeOutput, OpenScoringDisputeInput, OpenScoringDisputeOutput } from "../dto/dispute.dto";
export interface DisputeRepository {
  openScoringDispute(input: OpenScoringDisputeInput): Promise<OpenScoringDisputeOutput>;
  getScoringDispute(input: GetScoringDisputeInput): Promise<GetScoringDisputeOutput>;
}

export type { GetScoringDisputeInput, GetScoringDisputeOutput, OpenScoringDisputeInput, OpenScoringDisputeOutput } from "../dto/dispute.dto";
