/**
 * ReplayRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReplayRepository Port
 *
 * DDD: Application port for replayrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReplayDisputeEvaluationInput, ReplayDisputeEvaluationOutput } from "../dto/replay.dto";
export interface ReplayRepository {
  replayDisputeEvaluation(input: ReplayDisputeEvaluationInput): Promise<ReplayDisputeEvaluationOutput>;
}

export type { ReplayDisputeEvaluationInput, ReplayDisputeEvaluationOutput } from "../dto/replay.dto";
