/**
 * ValidationSnapshotRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValidationSnapshotRepository Port
 *
 * DDD: Application port for validationsnapshotrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateValidationSnapshotInput, CreateValidationSnapshotOutput, GetValidationSnapshotInput, GetValidationSnapshotOutput } from "../dto/validation-snapshot.dto";
export interface ValidationSnapshotRepository {
  createValidationSnapshot(input: CreateValidationSnapshotInput): Promise<CreateValidationSnapshotOutput>;
  getValidationSnapshot(input: GetValidationSnapshotInput): Promise<GetValidationSnapshotOutput>;
}

export type { CreateValidationSnapshotInput, CreateValidationSnapshotOutput, GetValidationSnapshotInput, GetValidationSnapshotOutput } from "../dto/validation-snapshot.dto";
