/**
 * Routes for Submission
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getModelSubmission, listModelSubmissions, submitModelArtifact } from "../handlers/submission.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ModelSubmissionRequest } from "@fedbounty/core/submissions/types";

// Fastify types are available globally
export async function submissionRoutes(fastify: FastifyInstance) {
  // GET /v1/submissions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/submissions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await listModelSubmissions(request, reply, deps);
      });
    }
  );


  // POST /v1/submissions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/submissions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ModelSubmissionRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await submitModelArtifact(request, reply, deps);
      });
    }
  );


  // GET /v1/submissions/{submissionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/submissions/:submissionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await getModelSubmission(request, reply, deps);
      });
    }
  );


}
