/**
 * GetScoringDispute handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getScoringDispute } from "@fedbounty/api-server/domains/validations/handlers";
import type { ValidationsDDDDependencies } from "@fedbounty/api-server/domains/validations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { VALIDATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetScoringDispute", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ValidationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ValidationsDDDDependencies>(
      VALIDATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetScoringDispute, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { disputeId: entity.id };

    await getScoringDispute(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetScoringDispute.execute).toHaveBeenCalledWith(expect.objectContaining({ disputeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { disputeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetScoringDispute, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getScoringDispute(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
