/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBountiesDomainModule } from "./bounties/dependencies/bounties-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildLineageDomainModule } from "./lineage/dependencies/lineage-ddd.dependencies.js";
export { buildReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export { buildRewardsDomainModule } from "./rewards/dependencies/rewards-ddd.dependencies.js";
export { buildSubmissionsDomainModule } from "./submissions/dependencies/submissions-ddd.dependencies.js";
export { buildValidationsDomainModule } from "./validations/dependencies/validations-ddd.dependencies.js";

// Export all domain dependency types
export type { BountiesDomainModule } from "./bounties/dependencies/bounties-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { LineageDomainModule } from "./lineage/dependencies/lineage-ddd.dependencies.js";
export type { ReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export type { RewardsDomainModule } from "./rewards/dependencies/rewards-ddd.dependencies.js";
export type { SubmissionsDomainModule } from "./submissions/dependencies/submissions-ddd.dependencies.js";
export type { ValidationsDomainModule } from "./validations/dependencies/validations-ddd.dependencies.js";
