/**
 * Routes for Dispute
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getScoringDispute, openScoringDispute } from "../handlers/dispute.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { DisputeOpenRequest } from "@fedbounty/core/validations/types";

// Fastify types are available globally
export async function disputeRoutes(fastify: FastifyInstance) {
  // POST /v1/disputes (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/disputes",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: DisputeOpenRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await openScoringDispute(request, reply, deps);
      });
    }
  );


  // GET /v1/disputes/{disputeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/disputes/:disputeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await getScoringDispute(request, reply, deps);
      });
    }
  );


}
