/**
 * Routes for Replay
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { replayDisputeEvaluation } from "../handlers/replay.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function replayRoutes(fastify: FastifyInstance) {
  // POST /v1/disputes/{disputeId}/replay (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/disputes/:disputeId/replay",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { disputeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await replayDisputeEvaluation(request, reply, deps);
      });
    }
  );


}
