/**
 * Routes for Validation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEvaluationResult, listEvaluationResults, runHoldoutValidation } from "../handlers/validation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { HoldoutValidationRequest } from "@fedbounty/core/validations/types";

// Fastify types are available globally
export async function validationRoutes(fastify: FastifyInstance) {
  // GET /v1/validations (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/validations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await listEvaluationResults(request, reply, deps);
      });
    }
  );


  // POST /v1/validations (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/validations",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: HoldoutValidationRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await runHoldoutValidation(request, reply, deps);
      });
    }
  );


  // GET /v1/validations/{evaluationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/validations/:evaluationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { evaluationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationsDependenciesForRequest();
        await getEvaluationResult(request, reply, deps);
      });
    }
  );


}
