/**
 * Bounty Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/bounties.openapi.types.js";
import { schemas } from "../schemas/bounties.schemas.js";

/**
 * Entity: BountyEntity
 * Description: Represents the Bounty domain model.
 * Source: schemas.Bounty
 * Type: Domain Entity (API)
 */
export const BountyEntitySchema = schemas.Bounty;
export type BountyEntity = components["schemas"]["Bounty"];
