/**
 * Pin DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pin DTOs
 *
 * DDD: Application DTOs for Pin use cases.
 */

import type { PinCanonicalModelVersionParams } from "@fedbounty/core/lineage/types";

export type PinCanonicalModelVersionInput = PinCanonicalModelVersionParams;

export type PinCanonicalModelVersionOutput = {};
