/**
 * Version DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Version DTOs
 *
 * DDD: Application DTOs for Version use cases.
 */

import type { GetModelVersionParams, ListModelVersionsParams, ModelMergeRequest } from "@fedbounty/core/lineage/types";

export type ListModelVersionsInput = ListModelVersionsParams;

export type MergeModelVersionInput = ModelMergeRequest;

export type GetModelVersionInput = GetModelVersionParams;

export type ListModelVersionsOutput = {};

export type MergeModelVersionOutput = {};

export type GetModelVersionOutput = {};
