/**
 * ExecutePinCanonicalModelVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePinCanonicalModelVersion Use Case
 *
 * DDD: Application use case for get Pin.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PinCanonicalModelVersionInput, PinCanonicalModelVersionOutput } from "../dto/pin.dto";
import type { ExecutionContextService, IdGeneratorService } from "@fedbounty/services/_shared/index.js";
import type { PinRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePinCanonicalModelVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pin: PinRepository
  ) {}

  async execute(input: PinCanonicalModelVersionInput): Promise<PinCanonicalModelVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.lngId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).versionId) {
      throw new ValidationError("versionId is required");
    }
    const versionId = (input as any).versionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.pin.pinCanonicalModelVersion({ versionId: versionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${versionId}`);
    }

    return entity as PinCanonicalModelVersionOutput;
  }
}
