/**
 * BountyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BountyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BountyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BountyRepository,
} from "@fedbounty/services/bounties";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BountyRepositoryDdb } from "./bounty-repository.ddb.js";

/**
 * BountyRepositoryAdapter
 *
 * Implements BountyRepository port for infrastructure layer.
 */
export class BountyRepositoryAdapter implements BountyRepository {
  private readonly ddb: BountyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BountyRepositoryDdb(this.dynamoClient);
  }

  async listBounties(input: Parameters<BountyRepository['listBounties']>[0]): Promise<Awaited<ReturnType<BountyRepository['listBounties']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBounties(input);
  }

  async createBounty(input: Parameters<BountyRepository['createBounty']>[0]): Promise<Awaited<ReturnType<BountyRepository['createBounty']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createBounty(input);
  }

  async getBounty(input: Parameters<BountyRepository['getBounty']>[0]): Promise<Awaited<ReturnType<BountyRepository['getBounty']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBounty(input);
  }

  async updateBounty(input: Parameters<BountyRepository['updateBounty']>[0]): Promise<Awaited<ReturnType<BountyRepository['updateBounty']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateBounty(input);
  }
}
