/**
 * EnrollmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EnrollmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EnrollmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EnrollmentRepository,
} from "@fedbounty/services/bounties";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EnrollmentRepositoryDdb } from "./enrollment-repository.ddb.js";

/**
 * EnrollmentRepositoryAdapter
 *
 * Implements EnrollmentRepository port for infrastructure layer.
 */
export class EnrollmentRepositoryAdapter implements EnrollmentRepository {
  private readonly ddb: EnrollmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EnrollmentRepositoryDdb(this.dynamoClient);
  }

  async listBountyEnrollments(input: Parameters<EnrollmentRepository['listBountyEnrollments']>[0]): Promise<Awaited<ReturnType<EnrollmentRepository['listBountyEnrollments']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listBountyEnrollments(input);
  }

  async enrollWorker(input: Parameters<EnrollmentRepository['enrollWorker']>[0]): Promise<Awaited<ReturnType<EnrollmentRepository['enrollWorker']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.enrollWorker(input);
  }
}
