/**
 * FreezeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FreezeRepository Port
 *
 * DDD: Application port for freezerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { FreezeBountyInput, FreezeBountyOutput } from "../dto/freeze.dto";
export interface FreezeRepository {
  freezeBounty(input: FreezeBountyInput): Promise<FreezeBountyOutput>;
}

export type { FreezeBountyInput, FreezeBountyOutput } from "../dto/freeze.dto";
