/**
 * ValidationSnapshotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ValidationSnapshotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ValidationSnapshotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ValidationSnapshotRepository,
} from "@fedbounty/services/validations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ValidationSnapshotRepositoryDdb } from "./validation-snapshot-repository.ddb.js";

/**
 * ValidationSnapshotRepositoryAdapter
 *
 * Implements ValidationSnapshotRepository port for infrastructure layer.
 */
export class ValidationSnapshotRepositoryAdapter implements ValidationSnapshotRepository {
  private readonly ddb: ValidationSnapshotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ValidationSnapshotRepositoryDdb(this.dynamoClient);
  }

  async createValidationSnapshot(input: Parameters<ValidationSnapshotRepository['createValidationSnapshot']>[0]): Promise<Awaited<ReturnType<ValidationSnapshotRepository['createValidationSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createValidationSnapshot(input);
  }

  async getValidationSnapshot(input: Parameters<ValidationSnapshotRepository['getValidationSnapshot']>[0]): Promise<Awaited<ReturnType<ValidationSnapshotRepository['getValidationSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getValidationSnapshot(input);
  }
}
