/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Validations Domain Use Cases
 * 
 * List of all use case names for the validations domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VALIDATIONS_USE_CASES = [
  "executeCreateValidationSnapshot",
  "executeGetEvaluationResult",
  "executeGetScoringDispute",
  "executeGetValidationSnapshot",
  "executeListEvaluationResults",
  "executeOpenScoringDispute",
  "executeReplayDisputeEvaluation",
  "executeRunHoldoutValidation"
] as const;
