/**
 * SubmissionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmissionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubmissionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubmissionRepository,
} from "@fedbounty/services/submissions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubmissionRepositoryDdb } from "./submission-repository.ddb.js";

/**
 * SubmissionRepositoryAdapter
 *
 * Implements SubmissionRepository port for infrastructure layer.
 */
export class SubmissionRepositoryAdapter implements SubmissionRepository {
  private readonly ddb: SubmissionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubmissionRepositoryDdb(this.dynamoClient);
  }

  async listModelSubmissions(input: Parameters<SubmissionRepository['listModelSubmissions']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['listModelSubmissions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelSubmissions(input);
  }

  async submitModelArtifact(input: Parameters<SubmissionRepository['submitModelArtifact']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['submitModelArtifact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitModelArtifact(input);
  }

  async getModelSubmission(input: Parameters<SubmissionRepository['getModelSubmission']>[0]): Promise<Awaited<ReturnType<SubmissionRepository['getModelSubmission']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModelSubmission(input);
  }
}
