/**
 * PauseEscrow handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { pauseEscrow } from "@fedbounty/api-server/domains/rewards/handlers";
import type { RewardsDDDDependencies } from "@fedbounty/api-server/domains/rewards";
import { createCreatePauseRequest } from "@fedbounty/factories/rewards";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { REWARDS_USE_CASES } from "../__factories__/use-cases.js";

describe("PauseEscrow", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: RewardsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<RewardsDDDDependencies>(
      REWARDS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePauseRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePauseEscrow, "execute").mockResolvedValue(useCaseResult);

    await pauseEscrow(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePauseEscrow.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
