/**
 * Validation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Validation DTOs
 *
 * DDD: Application DTOs for Validation use cases.
 */

import type { GetEvaluationResultParams, HoldoutValidationRequest, ListEvaluationResultsParams } from "@fedbounty/core/validations/types";

export type ListEvaluationResultsInput = ListEvaluationResultsParams;

export type RunHoldoutValidationInput = HoldoutValidationRequest;

export type GetEvaluationResultInput = GetEvaluationResultParams;

export type ListEvaluationResultsOutput = {};

export type RunHoldoutValidationOutput = {};

export type GetEvaluationResultOutput = {};
