/**
 * Payout DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Payout DTOs
 *
 * DDD: Application DTOs for Payout use cases.
 */

import type { GetRewardPayoutParams, ListRewardPayoutsParams, RewardPayoutRequest } from "@fedbounty/core/rewards/types";

export type ListRewardPayoutsInput = ListRewardPayoutsParams;

export type ExecuteRewardPayoutInput = RewardPayoutRequest;

export type GetRewardPayoutInput = GetRewardPayoutParams;

export type ListRewardPayoutsOutput = {};

export type ExecuteRewardPayoutOutput = {};

export type GetRewardPayoutOutput = {};
