/**
 * CreateValidationSnapshot DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ValidationSnapshotCreateRequest } from "@fedbounty/core/validations";
import { validationsSchemas } from "@fedbounty/core/validations";

export function createCreateValidationSnapshotRequest(overrides: Partial<ValidationSnapshotCreateRequest> = {}) {
  const raw = {
    metricName: overrides.metricName ?? faker.lorem.word(),
    ...overrides,
  };

  return validationsSchemas.ValidationSnapshotCreateRequest.parse(raw);
}
