/**
 * CreateFreeze DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { BountyFreezeRequest } from "@fedbounty/core/bounties";
import { bountiesSchemas } from "@fedbounty/core/bounties";

export function createCreateFreezeRequest(overrides: Partial<BountyFreezeRequest> = {}) {
  const raw = {
    reason: overrides.reason ?? faker.lorem.word(),
    ...overrides,
  };

  return bountiesSchemas.BountyFreezeRequest.parse(raw);
}
