/**
 * Handlers for Quarantine
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubmissionsDomainModule } from "../dependencies/submissions-ddd.dependencies.js";
import type { SubmissionQuarantineRequest } from "@fedbounty/core/submissions/types";
import type { QuarantineModelSubmissionInput } from "@fedbounty/services/submissions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/submissions/{submissionId}/quarantine
 * Operation: quarantineModelSubmission
 */
export async function quarantineModelSubmission(
  request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: SubmissionQuarantineRequest }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: QuarantineModelSubmissionInput = {
    submissionId: request.params.submissionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quarantines.get.execute(input);
  return reply.code(200).send(result);
}


