/**
 * Handlers for Submission
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubmissionsDomainModule } from "../dependencies/submissions-ddd.dependencies.js";
import type { ModelSubmissionRequest } from "@fedbounty/core/submissions/types";
import type { GetModelSubmissionInput, ListModelSubmissionsInput, SubmitModelArtifactInput } from "@fedbounty/services/submissions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/submissions
 * Operation: listModelSubmissions
 */
export async function listModelSubmissions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], bountyId?: string | string[], workerId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListModelSubmissionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.submissions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/submissions
 * Operation: submitModelArtifact
 */
export async function submitModelArtifact(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ModelSubmissionRequest }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitModelArtifactInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.submissions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/submissions/{submissionId}
 * Operation: getModelSubmission
 */
export async function getModelSubmission(
  request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetModelSubmissionInput = {
    submissionId: request.params.submissionId,
  };
  const result = await deps.useCases.submissions.get.execute(input);
  return reply.code(200).send(result);
}


