/**
 * PayoutRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PayoutRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PayoutRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PayoutRepository,
} from "@fedbounty/services/rewards";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PayoutRepositoryDdb } from "./payout-repository.ddb.js";

/**
 * PayoutRepositoryAdapter
 *
 * Implements PayoutRepository port for infrastructure layer.
 */
export class PayoutRepositoryAdapter implements PayoutRepository {
  private readonly ddb: PayoutRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PayoutRepositoryDdb(this.dynamoClient);
  }

  async listRewardPayouts(input: Parameters<PayoutRepository['listRewardPayouts']>[0]): Promise<Awaited<ReturnType<PayoutRepository['listRewardPayouts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRewardPayouts(input);
  }

  async executeRewardPayout(input: Parameters<PayoutRepository['executeRewardPayout']>[0]): Promise<Awaited<ReturnType<PayoutRepository['executeRewardPayout']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executeRewardPayout(input);
  }

  async getRewardPayout(input: Parameters<PayoutRepository['getRewardPayout']>[0]): Promise<Awaited<ReturnType<PayoutRepository['getRewardPayout']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRewardPayout(input);
  }
}
