/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-bounty.handler.test.js";
export * from "./get-bounty.handler.test.js";
export * from "./list-bounties.handler.test.js";
export * from "./update-bounty.handler.test.js";
