/**
 * ListBounties handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listBounties } from "@fedbounty/api-server/domains/bounties/handlers";
import type { BountiesDDDDependencies } from "@fedbounty/api-server/domains/bounties";
import { createBounty as createBountyEntity } from "@fedbounty/factories/bounties";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { BOUNTIES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListBounties", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BountiesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BountiesDDDDependencies>(
      BOUNTIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createBountyEntity({ orgId }),
      createBountyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListBounties, "execute").mockResolvedValue(useCaseResult);

    await listBounties(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListBounties.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
