/**
 * PayoutRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PayoutRepository Port
 *
 * DDD: Application port for payoutrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecuteRewardPayoutInput, ExecuteRewardPayoutOutput, GetRewardPayoutInput, GetRewardPayoutOutput, ListRewardPayoutsInput, ListRewardPayoutsOutput } from "../dto/payout.dto";
export interface PayoutRepository {
  listRewardPayouts(input: ListRewardPayoutsInput): Promise<ListRewardPayoutsOutput>;
  executeRewardPayout(input: ExecuteRewardPayoutInput): Promise<ExecuteRewardPayoutOutput>;
  getRewardPayout(input: GetRewardPayoutInput): Promise<GetRewardPayoutOutput>;
}

export type { ExecuteRewardPayoutInput, ExecuteRewardPayoutOutput, GetRewardPayoutInput, GetRewardPayoutOutput, ListRewardPayoutsInput, ListRewardPayoutsOutput } from "../dto/payout.dto";
