/**
 * PinCanonicalModelVersion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { pinCanonicalModelVersion } from "@fedbounty/api-server/domains/lineage/handlers";
import type { LineageDDDDependencies } from "@fedbounty/api-server/domains/lineage";
import { createCreatePinRequest } from "@fedbounty/factories/lineage";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@fedbounty/tests/shared";
import { LINEAGE_USE_CASES } from "../__factories__/use-cases.js";

describe("PinCanonicalModelVersion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LineageDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LineageDDDDependencies>(
      LINEAGE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreatePinRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executePinCanonicalModelVersion, "execute").mockResolvedValue(useCaseResult);

    await pinCanonicalModelVersion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executePinCanonicalModelVersion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
