/**
 * CreateQuarantine DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SubmissionQuarantineRequest } from "@fedbounty/core/submissions";
import { submissionsSchemas } from "@fedbounty/core/submissions";

export function createCreateQuarantineRequest(overrides: Partial<SubmissionQuarantineRequest> = {}) {
  const raw = {
    reason: overrides.reason ?? faker.lorem.word(),
    ...overrides,
  };

  return submissionsSchemas.SubmissionQuarantineRequest.parse(raw);
}
