/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Submissions Domain Use Cases
 * 
 * List of all use case names for the submissions domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SUBMISSIONS_USE_CASES = [
  "executeGetModelSubmission",
  "executeListModelSubmissions",
  "executeQuarantineModelSubmission",
  "executeSubmitModelArtifact"
] as const;
