/**
 * Bounty DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Bounty DTOs
 *
 * DDD: Application DTOs for Bounty use cases.
 */

import type { BountyCreateRequest, BountyUpdateRequest, GetBountyParams, ListBountiesParams, UpdateBountyParams } from "@fedbounty/core/bounties/types";

export type ListBountiesInput = ListBountiesParams;

export type CreateBountyInput = BountyCreateRequest;

export type GetBountyInput = GetBountyParams;

export type UpdateBountyInput = UpdateBountyParams & BountyUpdateRequest;

export type ListBountiesOutput = {};

export type CreateBountyOutput = {};

export type GetBountyOutput = {};

export type UpdateBountyOutput = {};
