/**
 * Freeze DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bounties
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Freeze DTOs
 *
 * DDD: Application DTOs for Freeze use cases.
 */

import type { BountyFreezeRequest, FreezeBountyParams } from "@fedbounty/core/bounties/types";

export type FreezeBountyInput = FreezeBountyParams & BountyFreezeRequest;

export type FreezeBountyOutput = {};
