/**
 * GetPayout DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: rewards
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRewardPayoutParams } from "@fedbounty/core/rewards";

export function createGetPayoutRequest(overrides: Partial<GetRewardPayoutParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
